"""empty message

Revision ID: 0793b05f6324
Revises: 53805ad29559
Create Date: 2021-11-06 21:47:31.745994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0793b05f6324'
down_revision = '53805ad29559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detailed_invoice_description_key', 'detailed_invoice', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('detailed_invoice_description_key', 'detailed_invoice', ['description'])
    # ### end Alembic commands ###
