"""empty message

Revision ID: 668287e53ae9
Revises: ba2456b778ca
Create Date: 2021-11-17 21:39:17.116512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668287e53ae9'
down_revision = 'ba2456b778ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailed_invoice', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('detailed_invoice', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailed_invoice', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('detailed_invoice', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
