"""empty message

Revision ID: 834dfa468076
Revises: c02b85b7c8af
Create Date: 2021-11-13 18:28:46.080574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834dfa468076'
down_revision = 'c02b85b7c8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_description_key', 'invoice', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('invoice_description_key', 'invoice', ['description'])
    # ### end Alembic commands ###
