"""empty message

Revision ID: 8536c7358098
Revises: a19294702054
Create Date: 2021-11-16 21:09:14.232132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8536c7358098'
down_revision = 'a19294702054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailed_invoice', sa.Column('id_group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detailed_invoice', 'groups', ['id_group'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detailed_invoice', type_='foreignkey')
    op.drop_column('detailed_invoice', 'id_group')
    # ### end Alembic commands ###
