"""empty message

Revision ID: ba2456b778ca
Revises: dbb2e7cfd6e5
Create Date: 2021-11-17 21:23:45.905572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2456b778ca'
down_revision = 'dbb2e7cfd6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Wallet')
    op.add_column('detailed_invoice', sa.Column('source', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detailed_invoice', 'source')
    op.create_table('Wallet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Wallet_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='Wallet_id_user_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Wallet_pkey')
    )
    op.drop_table('wallet')
    # ### end Alembic commands ###
