"""empty message

Revision ID: bee258ea7178
Revises: 0793b05f6324
Create Date: 2021-11-07 11:32:34.158979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee258ea7178'
down_revision = '0793b05f6324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detailed_invoice_id_invoice_fkey', 'detailed_invoice', type_='foreignkey')
    op.create_foreign_key(None, 'detailed_invoice', 'invoice', ['id_invoice'], ['id'], ondelete='CASCADE')
    op.drop_constraint('entry_id_source_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key(None, 'entry', 'source', ['id_source'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key('entry_id_source_fkey', 'entry', 'source', ['id_source'], ['id'])
    op.drop_constraint(None, 'detailed_invoice', type_='foreignkey')
    op.create_foreign_key('detailed_invoice_id_invoice_fkey', 'detailed_invoice', 'invoice', ['id_invoice'], ['id'])
    # ### end Alembic commands ###
